import React, {Component, Children, cloneElement} from 'react'
import PropTypes from 'prop-types'
import styled, {css} from 'styled-components'
import {observer} from 'mobx-react'
import {range} from '@dekk/utils'
import Store from '@dekk/store'
import Slide from '@dekk/slide'
import {search} from '@dekk/url'
import Wrapper from './wrapper'
import SlidesWrapper from './slides-wrapper'

export {default as Plugins} from './plugins'
export {default as Elements} from './elements'
export {default as SpeakerDeck} from './speaker-deck'
export {default} from './deck'
