const path = require('path')
const {writeFileSync} = require('fs')
const documentation = require('documentation')
const globby = require('globby')

const addHeader = (md, file) => {
  const prettyName = file.replace(/@dekk\//g, '').replace(/\/src\//g, '/')
  return `---
displayName: "Docs: ${prettyName}"
tags: 
  - Docs
---

${md}
`
}

globby([
  '@dekk/*/src/**/*.js',
  '!@dekk/*/src/**/demo.js',
  '!@dekk/**/node_modules'
])
  .then(files => {
    files.forEach(file => {
      documentation
        .build([file], {shallow: true})
        .then(documentation.formats.md)
        .then(output => {
          const filename = file
            .replace(/@dekk\//g, '')
            .replace(/\/src\//g, '/')
            .replace(/\//g, '_')
            .replace(/\.js$/, '.md')

          if (
            output.trim() !==
            '<!-- Generated by documentation.js. Update this documentation by updating the source code. -->'
          ) {
            const text = addHeader(output, file)
            writeFileSync(
              path.resolve(__dirname, `../manual/jsdoc/${filename}`),
              text,
              err => {
                if (err) {
                  console.log(err)
                }
              }
            )
          }
        })
    })
  })
  .catch(console.error)
