export {default as Title} from './title'
export {default as Subtitle} from './subtitle'
export {default as Code, colorSchemes} from './code'
export {default as Quote} from './quote'
export {default as Center} from './center'
export {default as Bold} from './bold'
export {default as Uppercase} from './uppercase'
export {default} from './text'
